# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blockpile}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tyler Flint"]
  s.date = %q{2010-08-20}
  s.description = %q{This module attempts to create structured view helpers. Essentially, a blockpile consists of a ruby class file, and a template. This allows for isolated blocks of view logic, that can maintain a clean separation of markup language from ruby code. Blocks can be inherited from to DRY up view logic.}
  s.email = %q{tylerflint@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "blockpile.gemspec",
     "lib/blockpile.rb",
     "lib/blockpile/base.rb",
     "lib/blockpile/setup.rb",
     "lib/generators/blockpile/USAGE",
     "lib/generators/blockpile/blockpile_generator.rb",
     "lib/generators/blockpile/templates/blockpile.html.erb",
     "lib/generators/blockpile/templates/blockpile.rb",
     "lib/tasks/blockpile_tasks.rake",
     "test/blockpile_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/tylerflint/blockpile}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{piles of extendable rails view blocks, triggered and masked behind simple helpers}
  s.test_files = [
    "test/blockpile_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

